- name: install dependencies
  apt: 
    pkg: [curl] 
    update_cache: yes
  become: true

- name: install rustup
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: ~/.cargo

- name: install rust commands
  shell: |
    export PATH=$HOME/.cargo/bin:$PATH
    cargo install {{ item }}
  with_items: "{{ rust_commands }}"
