- name: install dependencies
  apt: pkg={{ item }} update_cache=yes
  sudo: True
  with_items:
    - curl

- name: install rustup
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

- name: install rust commands
  shell: cargo install {{ item }}
  with_items: {{ rust_commands }}
