- name: Setup development machine
  hosts: localhost
  vars_files: vars.yml
  pre_tasks:
    - name: Update the apt cache
      become: true
      apt: update_cache=yes
    
    - name: Check for python install
      stat: 
        path: ~/.pyenv
      register: pyenv_stat

    - name: Check for rust install
      stat: 
        path: ~/.cargo
      register: cargo_stat

    - name: Check for node install
      stat: 
        path: ~/.nvm
      register: nvm_stat

  roles:
    - role: configuration
    - role: python
      when: not pyenv_stat.stat.exists
    - role: rust
      when: not cargo_stat.stat.exists
    - role: node
      when: not nvm_stat.stat.exists
