- name: Setup development machine
  hosts: localhost
  vars_files: vars.yml
  pre_tasks:
    - name: Update the apt cache
      apt: update_cache=yes

  roles:
    - role: configuration
    - role: python
    - role: rust
