- name: install dependencies
  become: true
  apt: 
    pkg: 
      - git
      - zsh
    update_cache: yes

- name: checkout config directory
  git:
    repo: git@github.com:dbradf/configfiles.git
    dest: ~/etc/configfiles

- name: install configuration
  shell: ./install
  args:
    chdir: ~/etc/configfiles

- name: setup zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
