- name: install dependencies
  become: true
  apt: 
    pkg: 
      - git
      - zsh
    update_cache: yes

- name: checkout config directory
  git:
    repo: "{{ configuration_repo }}"
    dest: ~/etc/configfiles

- name: install configuration
  shell: "{{ configuration_install_cmd }}"
  args:
    chdir: ~/etc/configfiles

- name: setup zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
