- name: install dependencies
  apt: 
    pkg:
      - git
      - curl
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev 
      - libsqlite3-dev 
      - wget 
      - llvm 
      - libncurses5-dev 
      - libncursesw5-dev
      - xz-utils 
      - tk-dev 
      - libffi-dev 
      - liblzma-dev 
      - python-openssl
    update_cache: yes
  become: True

- name: install pyenv
  shell: curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash

- name: install python versions
  shell: |
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"

    pyenv install {{ item }}
  with_items: "{{ python_versions }}"

- name: Configure global python version
  shell: |
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"

    pyenv global {{ python_versions[0] }}

- name: Install pipx
  shell: |
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"

    pip install pipx

- name: Install poetry
  shell: |
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"

    pipx install poetry
